name: Build and Deploy to Sandbox

on:
  push:
    branches: [ Irfaan-dev1 ]
  pull_request:
    branches: [ Irfaan-dev1 ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 8

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Stamp artifact file name with commit hash
      run: |
        artifactName1=$(ls target/*.jar | head -1)
        commitHash=$(git rev-parse --short "$GITHUB_SHA")
        artifactName2=$(ls target/*.jar | head -1 | sed "s/.jar/-$commitHash.jar/g")
        mv $artifactName1 $artifactName2

    - name: Upload artifact 
      uses: actions/upload-artifact@v4
      with:
          name: artifacts
          path: target/*.jar
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:    
    - name: Checkout this repo
      uses: actions/checkout@v4

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - uses: actions/download-artifact@v4
      with: 
          name: artifacts

    
    - name: Publish to Exchange
      run: | 
        artifactName=$(ls *.jar | head -1)
        mvn deploy --settings .maven/settings.xml -DskipMunitTests \
        -Dclient.id="${{ secrets.ANYPOINT_CONNECTED_APP_ID }}" \
        -Dclient.secret="${{ secrets.ANYPOINT_CONNECTED_APP_SECRET }}"

    - name: Deploy to Cloudhub 2.0
      env:
        UAT_CLIENT_ID: ${{ secrets.ANYPOINT_UAT_CLIENT_ID }}
        UAT_CLIENT_SECRET: ${{ secrets.ANYPOINT_UAT_CLIENT_SECRET }}
      run: |
        artifactName=$(ls *.jar | head -1)
        mvn deploy -DmuleDeploy --settings .maven/settings.xml -DskipMunitTests \
          -Danypoint.client_id="$UAT_CLIENT_ID" \
          -Danypoint.client_secret="$UAT_CLIENT_SECRET" \
          -Dconnectedapp.id="${{ secrets.ANYPOINT_CONNECTED_APP_ID }}" \
          -Dconnectedapp.secret="${{ secrets.ANYPOINT_CONNECTED_APP_SECRET }}"